# # source('config.R')
# source('R/preprocessing.R')
# tryCatch({
#   source("R/function_docs.R")
# }, error = function(e) {
#   cat("Documentation file 'function_docs.R' not found. Proceeding without documentation.\n")
# })
# library(RCurl)

# # Then, reassign the docstrings
# if (exists("function_docs", envir = .GlobalEnv)) {
#   for (func_name in names(function_docs)) {
#     if (exists(func_name, envir = .GlobalEnv)) {
#       func <- get(func_name, envir = .GlobalEnv)
#       assign(func_name, structure(func, doc = function_docs[[func_name]]), envir = .GlobalEnv)    }
#   }
# }
# #TODO: Clean this up try to reduce the unnecessary output generated by R and add this info somewhere on the ReadMe
# doc("extract_meta_data")
# doc("preprocess_WRIC_file")

source("R/preprocessing.R")

# no_comment_file = "/Users/au698484/Documents/data_wric_no_comment.txt"
result <- preprocess_WRIC_file("example_data/data.txt", notefilepath="example_data/note.txt")#, start="2023-11-13 11:43:00", end="2023-11-13 12:09:00") # "C:/Documents/WRIC_example_data/Main_note_yyyymmddxxxx.txt"
R1_metadata <- result$R1_metadata
R2_metadata <- result$R2_metadata
df_room1 <- result$df_room1
df_room2 <- result$df_room2

print("Now the second task!")
#TODO: Seperate problem: The drift row is asigned to partciipant 2? But not problem, right?

# # str(df_room1)



# print("Done")
#tr(df_room1)

#dataframes <- preprocess_WRIC_files('id.csv', 'upload')

# Example: Access `df_room1` for a specific record ID (e.g., record ID 12345)
#df_room1_example <- dataframes[["2"]]$df_room1
# str(df_room1_example)

# avoid cross-plattform errors by setting the certificate globally
#download.file(url = "https://curl.se/ca/cacert.pem", destfile = "cacert.pem")
#options(RCurlOptions = list(cainfo = "cacert.pem"))

#file_path <- './tmp/export.raw.txt'
#file_content <- paste(readLines(file_path), collapse = "\n")

#result <- postForm(
#    api_url,
#    token=api_token,
#    content='file',
#    action='import',
#    record='2',
#    field='upload',
#    returnFormat='json',
#    file = file_content
#)

#result = detect_start_end("C:/Documents/WRIC_example_data/Main_note_yyyymmddxxxx.txt")
#print(result)
#print(result[1])

# notes_path = "C:/Documents/WRIC_example_data/Main_note_yyyymmddxxxx.txt"
# returns = extract_note_info(notes_path, df_room1, df_room2)
# df_room1 <- returns$df_room1
# df_room2 <- returns$df_room2
#str(df_room1)

?extract_note_info

# processing of Simon's data 
# TODO: Actually convert all the analysis done in Python into R and a coherent script

# Define the dictionary as a named list
wric_dict <- list(
  "01JJ_wric1min_v1_treat0.txt" = "01JJ_wric1min_v1_note_treat0.txt", 
  "01JJ_wric1min_v2_treat1.txt" = "01JJ_wric1min_v2_note_treat1.txt", 
  "02LK_v2_treat0_wric1min_04HH_v2_treat1.txt" = "02LK_v2_treat0_wric1min_04HH_v2_treat1_note.txt", 
  "02LK_wric1min_v1_treat1.txt" = "02LK_wric1min_v1_note_treat1.txt", 
  "03HA_v1_treat1_wric1min_04HH_v1_treat0.txt" = "03HA_v1_treat1_wric1min_04HH_v1_treat0_note.txt", 
  "03HA_wric1min_v2_treat0.txt" = "03HA_wric1min_v2_note_treat0.txt", 
  # "05PM_wric1min_v1_treat0.txt" = "05PM_wric1min_v1_note_treat0.txt",  # Commented out
  "05PM_wric1min_v2_treat1.txt" = "05PM_wric1min_v2_note_treat1.txt", 
  "06ML_v2_treat1_wric1min_09NQ_v1_treat1.txt" = "06ML_v2_treat1_wric1min_09NQ_v1_treat1_note.txt", 
  "06ML_wric1min_v1_treat0.txt" = "06ML_wric1min_v1_note_treat0.txt", 
  "07AB_v1_treat1_wric1min_08MG_v2_treat0.txt" = "07AB_v1_treat1_wric1min_08MG_v2_treat0_note.txt", 
  "07AB_wric1min_v2_treat0.txt" = "07AB_wric1min_v2_note_treat0.txt", 
  "08MG_wric1min_v1_treat1.txt" = "08MG_wric1min_v1_note_treat1.txt", 
  "09NQ_wric1min_v2_treat0.txt" = "09NQ_wric1min_v2_note_treat0.txt", 
  "10JK_wric1min_v1_treat0.txt" = "10JK_wric1min_v1_note_treat0.txt", 
  "10JK_wric1min_v2_treat1.txt" = "10JK_wric1min_v2_note_treat1.txt"
)

# Define folder paths
base_folder <- "/Volumes/SUNSHINE/Simon_CIRCLE/WRIC/"
note_base_folder <- "/Volumes/SUNSHINE/Simon_CIRCLE/WRIC/Notes_Processed/"
path_to_save <- "/Volumes/SUNSHINE/Simon_CIRCLE/WRIC/processed/"

# Iterate over the dictionary
for (filepath in names(wric_dict)) {
  notepath <- wric_dict[[filepath]]
  print(paste(filepath, notepath))  # Print file paths
  
  # Call a hypothetical function equivalent to `wric.preprocess_WRIC_file`
  result <- preprocess_WRIC_file(
    paste0(base_folder, filepath),
    code = "id+comment",
    path_to_save = path_to_save,
    notefilepath = paste0(note_base_folder, notepath)
  )
}





# Example Usage

# Path to the folder containing the files
folder_path <- "/Volumes/SUNSHINE/Simon_CIRCLE/WRIC/processed"
# file <- "/Users/au698484/Documents/01JJ_v1_treat0_WRIC_data.csv"
# visualize_with_protocol(file, plot="Energy Expenditure (kcal/min)", 
#                         save_png = TRUE)


# Get all files ending with "_data.csv"
csv_files <- list.files(folder_path, pattern = "_data.csv", full.names = TRUE)
dataframes <- list()

protocol_colors_labels <- data.frame(
  protocol = c(0, 1, 2, 3, 4),
  color = c("white", "purple", "#4b3302", "#48c5a6", "#d0a4c6"),
  label = c("Normal", "Something", "Nothing", "Exercise", "RER")
)

for (file in csv_files) {
  #visualize_with_protocol(file) #plot="Energy Expenditure (kcal/min)"
  visualize_with_protocol(file, plot="Energy Expenditure (kcal/min)", 
                          protocol_colors_labels = protocol_colors_labels,
                          save_png = TRUE)
}